# Generated by Django 5.0.7 on 2024-07-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_html',
            field=models.TextField(blank=True),
        ),
    ]
