# Generated by Django 5.0.7 on 2024-07-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
