# Generated by Django 5.0.7 on 2024-07-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
